// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyQanwfwJzM-vQXEPdOb90Ua6z9hjSVaY',
    appId: '1:101754907553:web:03642d9cf4b2dbb43779e0',
    messagingSenderId: '101754907553',
    projectId: 'ascend-53cba',
    authDomain: 'ascend-53cba.firebaseapp.com',
    storageBucket: 'ascend-53cba.firebasestorage.app',
    measurementId: 'G-XG2G1R2KZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIfQdwX85a5pL_n1zcSCgLmwdb7RI7ZlY',
    appId: '1:101754907553:android:42c5697b36633c963779e0',
    messagingSenderId: '101754907553',
    projectId: 'ascend-53cba',
    storageBucket: 'ascend-53cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM87L1lRB6N6KJFUjx8Hv9NiieV_c8R2I',
    appId: '1:101754907553:ios:c192f22fd1c17c8e3779e0',
    messagingSenderId: '101754907553',
    projectId: 'ascend-53cba',
    storageBucket: 'ascend-53cba.firebasestorage.app',
    iosBundleId: 'com.example.ascend',
  );
}
